openapi: 3.0.1
info:
  title: MoDaC asset-details-controller delete-predictions-controller API
  description: MoDaC API is a set of public rest API to access datasets stored in the repository
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: delete-predictions-controller
paths:
  /deletePredictions:
    post:
      tags:
      - delete-predictions-controller
      operationId: deletePredictions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeletePredictionsModel'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    DeletePredictionsModel:
      type: object
      properties:
        deletepaths:
          type: string
        taskId:
          type: string
        predCollectionPath:
          type: string
