openapi: 3.0.1
info:
  title: MoDaC asset-details-controller doe-collection-controller API
  description: MoDaC API is a set of public rest API to access datasets stored in the repository
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: doe-collection-controller
paths:
  /collection:
    post:
      tags:
      - doe-collection-controller
      operationId: updateCollection
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DoeCollectionModel'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    HpcCollectionListingEntry:
      type: object
      properties:
        id:
          type: integer
          format: int32
        path:
          type: string
        dataSize:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        isSoftlink:
          type: boolean
    HpcCollection:
      type: object
      properties:
        collectionId:
          type: integer
          format: int32
        collectionName:
          type: string
        absolutePath:
          type: string
        collectionParentName:
          type: string
        collectionOwnerName:
          type: string
        collectionOwnerZone:
          type: string
        collectionMapId:
          type: string
        collectionInheritance:
          type: string
        comments:
          type: string
        info1:
          type: string
        info2:
          type: string
        createdAt:
          type: string
          format: date-time
        specColType:
          type: string
        isSoftlink:
          type: boolean
        subCollections:
          type: array
          items:
            $ref: '#/components/schemas/HpcCollectionListingEntry'
        dataObjects:
          type: array
          items:
            $ref: '#/components/schemas/HpcCollectionListingEntry'
        subCollectionsTotalRecords:
          type: integer
          format: int32
        dataObjectsTotalRecords:
          type: integer
          format: int32
    KeyValueBean:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
        displayName:
          type: string
        displayOrder:
          type: integer
          format: int32
    DoeMetadataAttrEntry:
      type: object
      properties:
        attrName:
          type: string
        attrValue:
          type: string
        attrUnit:
          type: string
        systemAttr:
          type: boolean
        validValues:
          type: array
          items:
            $ref: '#/components/schemas/KeyValueBean'
        defaultValue:
          type: string
        description:
          type: string
        mandatory:
          type: boolean
        displayName:
          type: string
        isEditable:
          type: boolean
        displayOrder:
          type: integer
          format: int32
        controllerAttribute:
          type: boolean
        isVisible:
          type: boolean
        isVisibleOnUplaodPage:
          type: boolean
        isVisibleForReviewCommiteeMember:
          type: boolean
        controllerAttrName:
          type: string
        controllerAttrValue:
          type: string
    DoeCollectionModel:
      type: object
      properties:
        path:
          type: string
        collection:
          $ref: '#/components/schemas/HpcCollection'
        selfMetadataEntries:
          type: array
          items:
            $ref: '#/components/schemas/DoeMetadataAttrEntry'
        parentMetadataEntries:
          type: array
          items:
            $ref: '#/components/schemas/DoeMetadataAttrEntry'
        attributes:
          type: object
          additionalProperties:
            type: string
        defaultValue:
          type: string
        validValues:
          type: array
          items:
            type: string
        dataObject:
          type: string
          writeOnly: true
